# Generated by Django 2.2.7 on 2019-11-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publiched_date',
            new_name='published_date',
        ),
    ]
